### ISSUE TITLE
Incorrect feature flags if `group` is called very quickly after initialization

### ISSUE THREAD

**Issue by roschlau** [PostHog/posthog-js#790] opened 2023-09-06 10:50 UTC
We're seeing an issue right now when we call `group` very quickly after posthog-js has initialized.

Our code structurally looks like this:

```typescript
posthog.init('...', {
  [...]
  loaded: (ph) => {
    ph.identify(...)
    ph.group(...) // This usually happens asynchronously, but dependent on posthog being initialized and very shortly afterwards
  }
})
```

What we're noticing is that with this setup, posthog initialization will trigger a `decide` call in the background, and the `group` call will also trigger another one, but the two are not synchronized, and if the `group`-triggered call finishes first, its results will be overwritten by the initialization-triggered one, leading to an incorrect state of feature flags (since the initial call doesn't have the correct values for the current group) down the line, until some other event happens that refreshes the feature flags again.
We can fix this by waiting until feature flags are loaded initially until we do the `group` call, but that's suboptimal since all events triggered until that point won't be attached to the group. Bootstrapping feature flags would also be a workaround, but is not easily possible for us.

Ideally, posthog-js would internally synchronize its `decide` calls and make sure that the `group`-triggered decide call will take precedence over the initial one. An alternative would also be, and this would be even better for us, to have an option to pass the group into the `initi` call already, so posthog knows what group to use from the start, eliminating all chances for this kind of race condition or events slipping through without a group ID assigned.

**Comment by neilkakkar** [comment] 2023-09-06 11:23
Hey @roschlau , looking into this. This shouldn't happen from what I can tell - we don't run requests in parallel, and the second one begins only after the first one has finished.

So, in effect, if you call `identify()` or `group()` several times, only a few requests should be triggered, and all in order.

What version of `posthog-js` are you on? And could you give me a minimal reproducible example please? Any other config you set / didn't set when calling init?

**Comment by Xyz3R** [comment] 2023-09-06 11:58
This race condition _only_ happened in combination with the request that was triggered by the initial page load. it is not reproducable by doing multiple subsequent `identify()` or `group()` call.

Instead, the group call has to happen very shortly after the inital pageload and right after initialising the `posthog-js` library.

During debugging we upgraded from version `1.68.5` to `1.77.2`. However, this  did not help. So I supposed the issue wasn't fixed in the meantime.

**Comment by neilkakkar** [comment] 2023-09-06 12:02
Ahh, I see, that makes some sense!

Right, that first initial call doesn't fit into this paradigm. Since you're calling immediately on load, I'd recommend setting https://posthog.com/docs/libraries/js#advanced-configuration -> `advanced_disable_feature_flags_on_first_load` to disable flags loading on that first call, which should fix this.

**Comment by Xyz3R** [comment] 2023-09-06 12:10
We also found that flag. And while this might fix this specific race condition, it caused us to run into some issues in other parts of our app where we rely on feature flags being available quickly. The group call during the app start only happens in one small (but important) part of our app. In most other parts, we don't have the information at that time.

We already built another workaround in this case, but as @roschlau mentioned it would be best for us to be able to bootstrap the library with a group identifier to already have that first decide call return the values we need :)

**Closed** 2023-09-07 11:19 UTC
