### ISSUE TITLE
PostHog Cookies Rejected warning messages on Prod

### ISSUE THREAD

**Issue by MarArMar** [PostHog/posthog-js#833] opened 2023-10-14 15:54 UTC
In browser logs, I have these messages, only on Prod (Localhost does not show the warnings in browser logs) :

Cookie “ph_phc_okLMsw7bwYpyho7m6B4ItKff0I5pObP1VAtIXB8096v_posthog” has been rejected for invalid domain. 5 [es.ae2e1b37.js:6:24224](https://____.vercel.app/_app/immutable/chunks/es.ae2e1b37.js)
Cookie “__ph_opt_in_out_phc_okLMsw7bwYpyho7m6B4ItKff0I5pObP1VAtIXB8096v” has been rejected for invalid domain. [es.ae2e1b37.js:6:24224](https:/__.vercel.app/_app/immutable/chunks/es.ae2e1b37.js)
Cookie “ph_phc_okLMsw7bwYpyho7m6B4ItKff0I5pObP1VAtIXB8096v_posthog” has been rejected for invalid domain. 3 [es.ae2e1b37.js:6:24224](https://___.vercel.app/_app/immutable/chunks/es.ae2e1b37.js)

Cookie “ph_phc_okLMsw7bwYpyho7m6B4ItKff0I5pObP1VAtIXB8096v_posthog” has been rejected for invalid domain.

## How to reproduce

    Create a SvelteKit project
    Install Posthog 
    Create Some buttons on your website with custom events
    Deploy on Vercel
    Click on Buttons
    Open browser logs
    Each time you clik on a button there is a new warning message
    

## Environment

PostHog Cloud US, project ID: 39279

## Additional context

"posthog-js": "^1.83.0",
"@sveltejs/kit": "^1.25.1",
"svelte": "^4.2.1",
"vite": "^4.4.9",

**Comment by daliendev** [comment] 2024-08-09 13:30
Same here (with PostHog Cloud EU).
But I see this warning message only in **Firefox** browser console, I made a test on a Chromium browser and it didn't show it.

In the end, it doesn't seem to have too much of an impact on operations. I can see the events going up even from such a Firefox client.

**Comment by pauldambra** [comment] 2024-08-19 21:25
Hey @MarArMar,

Sorry! This issue slipped by us... Yep, we detect the smallest non-public subdomain by setting cookies. You can't set `.com` for example https://github.com/PostHog/posthog-js/blob/83bedde2b02b87956c6d589ac0e58d2db32b0e8a/src/storage.ts#L19-L32

It is way more effective than the previous method but logs an error in firefox even though there's nothing wrong with what's happening.

I'll close this since it's not an issue _really_ although I'd be happy to hear of solutions if someone else knows of them since it would be way better to avoid the logged message - maybe someone knows someone who works on firefox 🤣

**Closed by pauldambra** 2024-08-19 21:25 UTC

**Comment by alfl** [comment] 2024-11-05 20:32
Generally speaking the console should run clean, and certainly shouldn't error when the behaviour is desired.

This might be "as designed" but then the design is not to standard.
