### ISSUE TITLE
Cannot find module 'types' or its corresponding type declarations in node_modules/posthog-js/dist/module.d.ts:1:52

### ISSUE THREAD

**Issue by jeremytenjo** [PostHog/posthog-js#712] opened 2023-06-23 16:23 UTC
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
![image](https://github.com/PostHog/posthog/assets/25231946/2d02b493-9203-47a9-be49-880e5a762c1d)

```js
node_modules/posthog-js/dist/module.d.ts:1:52 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

1 import { SurveyCallback as SurveyCallback$1 } from 'types';
```

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

1. install "posthog-js": "1.68.2"
2. npx tsc --noemit

## Environment

```json 
"posthog-js": "1.68.2",
"typescript": "4.7.4",
```

Thank you :)

**Comment by pauldambra** [comment] 2023-06-23 16:43
Duplicate of https://github.com/PostHog/posthog-js/issues/698

(I'll close this so we can keep just one @jeremytenjo but thanks for reporting 💖)

**Closed by pauldambra** 2023-06-23 16:43 UTC

**Comment by jeremytenjo** [comment] 2023-06-28 14:17
Thanks @pauldambra :D
