### ISSUE TITLE
'dangerouslySetInnerHTML' warning when initializing posthog and next-theme

### ISSUE THREAD

**Issue by msquinn** [PostHog/posthog-js#774] opened 2023-08-16 14:21 UTC
When I try to use posthog in addition to next-theme I get an error in the browser saying `Warning: Prop `dangerouslySetInnerHTML` did not match`. I'm using Next 13 app router. It seems as though adding my posthog provider to the layout component strips some attributes related to my theme from my project at build time, which later get applied and loaded client side, causing a mismatch. Here's[ a code sandbox](https://codesandbox.io/p/sandbox/goofy-pine-4h2wzn?file=/app/providers.tsx:14,1) with the minimal code to reproduce the issue. Note, to actually see the error in the sandbox you'll need to pass in your own API key for Posthog and view the application in it's own browser tab and then check the logs from there. 

![Screenshot 2023-08-16 at 9 08 36 AM](https://github.com/PostHog/posthog-js/assets/11398629/80457fcc-4814-44c0-a514-410801e4757e)

**Comment by jaxony** [comment] 2024-01-01 06:09
Also running into this issue, any fixes?

**Comment by financialvice** [comment] 2024-02-22 23:38
bumping this! having the same issue

**Comment by jakevollkommer** [comment] 2024-02-28 20:59
same issue here

**Comment by wladpaiva** [comment] 2024-04-28 00:04
I've narrow it down to the session recordings.

https://github.com/PostHog/posthog-js/assets/1843792/c1d80d03-d462-4d96-a38a-eacd7c16ad66

Everything else seems to be working fine

**Comment by andlipro** [comment] 2024-06-11 19:37
Can we init it after first render?
```
export default function CSPostHogProvider({ children }: { children: ReactNode }) {
    useEffect(() => {
        if (typeof window !== "undefined" && !posthog.__loaded) {
            posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY || "", { api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST });
        }
    }, []);
    return <PostHogProvider client={posthog}>{children}</PostHogProvider>;
}
```

**Comment by stormynight9** [comment] 2024-07-08 16:03
Has anybody found a solution for this?

**Comment by martinamps** [comment] 2024-07-10 20:03
+1 seeing this in remix with prop mismatches if I add posthog

**Comment by wladpaiva** [comment] 2024-07-11 14:29
The solution I've found for this is to create a new org for development only and disable screen recording on PH's dashboard

**Comment by pauldambra** [comment] 2024-07-11 19:04
hey all, sorry we missed this!

i'm just investigating to see what I can find out (but I'll admit to not having used SSR or Next JS much so feel free to prompt or correct me!)

---

[I've forked the supplied code sandbox](https://codesandbox.io/p/devbox/cool-ardinghelli-xtw8c6?file=%2Fapp%2Flayout.tsx%3A22%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyhjqvfg00083b6n2ua2ca4p%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyhjqvfg00033b6n09ty7fle%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyhjqvfg00053b6nifctnis0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyhjqvfg00073b6nokq03tjp%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyhjrefg002n3b6n0fls7d59%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyhjrfei00453b6nbk7x1tei%2522%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%252C0%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyhjqvfg00033b6n09ty7fle%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhjqvfg00023b6nz491o3wg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A64%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fproviders.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clyhlhhd900023b6m1dup4s56%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A22%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A22%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyhjqvfg00033b6n09ty7fle%2522%252C%2522activeTabId%2522%253A%2522clyhlhhd900023b6m1dup4s56%2522%257D%252C%2522clyhjqvfg00073b6nokq03tjp%2522%253A%257B%2522id%2522%253A%2522clyhjqvfg00073b6nokq03tjp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhjqvfg00063b6ng5sowsf7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clyhjqvfg00063b6ng5sowsf7%2522%257D%252C%2522clyhjqvfg00053b6nifctnis0%2522%253A%257B%2522id%2522%253A%2522clyhjqvfg00053b6nifctnis0%2522%252C%2522activeTabId%2522%253A%2522clyhjqvfg00043b6n7yyvcch3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhjqvfg00043b6n7yyvcch3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clyhmp8et00fr3b6md1tb6glj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clyhmp8he000lemgue6dggzch%2522%257D%255D%257D%252C%2522clyhjrefg002n3b6n0fls7d59%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhjqx6k002k3b6nmbu1z5z0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyhjrefg002n3b6n0fls7d59%2522%252C%2522activeTabId%2522%253A%2522clyhjqx6k002k3b6nmbu1z5z0%2522%257D%252C%2522clyhjrfei00453b6nbk7x1tei%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhjreue00403b6ncpotlfdn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyhjrfei00453b6nbk7x1tei%2522%252C%2522activeTabId%2522%253A%2522clyhjreue00403b6ncpotlfdn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and can replicate the issue whether or not I include posthog

That might only mean I'm confused about the problem :)

If I open the application in incognito mode then I don't get the error

Adding posthog back in using just the JS snippet (and in incognito mode) I don't get the error

And doing the same with the code sandbox in the initial OP I don't get an error in incognito but I do in my normal browser

-----

> So I originally posted my question a few [months back](https://nextjs.org/docs/messages/react-hydration-error).

@msquinn sorry you weren't happy with the response... you linked to the nextjs link in your comment so I can't follow up, but I'm happy to look into it 💖

**Comment by pauldambra** [comment] 2024-07-11 19:10
So, I'm only getting the error because I have the locator js extension installed

are others able to test if they still get the error in an incognito window or with all browser extensions disabled

(I'm super happy to investigate further but need to be able to consistently repro or i'll just be chasing my tail - and you all will know next/ssr better than me 😊)

**Comment by pauldambra** [comment] 2024-07-11 21:04
also see https://x.com/martinamps/status/1811491989084577911
https://github.com/martinamps/posthog-repro/tree/main

**Comment by jakevollkommer** [comment] 2024-07-11 21:07
We are indeed using radix components, specifically shadcn/ui

**Comment by pauldambra** [comment] 2024-07-11 22:14
so looking at the repro provided by martin i get the same error if i don't include posthog

```
import { RemixBrowser } from "@remix-run/react";
import { startTransition, StrictMode, useEffect } from "react";
import { hydrateRoot } from "react-dom/client";
// import posthog from "posthog-js";

function PosthogInit() {
  // useEffect(() => {
  //   posthog.init('phc_RpO1rh8u4ZgIDxSelv4kQDvyiyyty6iUiLpbs3sTOyb', {
  //     api_host: 'https://us.i.posthog.com',
  //     person_profiles: 'identified_only',
  //   });
  // }, []);

  return null;
}
startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
        <RemixBrowser />
        <PosthogInit/>   
    </StrictMode>
  );
});

```

causes the error

if you comment out `<PosthogInit/>` then the hydrate error goes away

(i also had to disable two browser extensions that caused a similar error in order to test this)

----

So, I could still be misunderstanding but still can't repro :)

**Comment by martinamps** [comment] 2024-07-12 14:01
We'll add this to the list of reasons I have largely avoided frontend for the past decade 😂 .... For remix at least, this may simply be a documentation issue.. some code googling/testing suggests this is a better implementation -- it works + no warnings:

```
import * as React from 'react';
import { RemixBrowser } from '@remix-run/react';
import { hydrateRoot } from 'react-dom/client';
import posthog from 'posthog-js';

function hydrate() {
  posthog.init('token', {
    api_host: 'https://us.i.posthog.com',
    person_profiles: 'identified_only',
  });

  React.startTransition(() => {
    hydrateRoot(
      document,
      <React.StrictMode>
        <RemixBrowser />
      </React.StrictMode>,
    );
  });
}

if (window.requestIdleCallback) {
  window.requestIdleCallback(hydrate);
} else {
  window.setTimeout(hydrate, 1);
}
```

disclaimer: I started learning Remix last week, so I'm no expert

**Comment by pauldambra** [comment] 2024-07-12 14:14
you've got a week on me @martinamps 🤣

**Comment by pauldambra** [comment] 2024-07-13 10:32
hey all, i'm going to close this so that future travellers see that the problem/solution here was never related to PostHog
and it's only that SSR is tricky

ofc if someone can come up with a repro of where posthog isn't working well here do reopen this or log a new issue - we love fixing things - i just can't find anything for us to fix here 😊 😌

**Closed by pauldambra** 2024-07-13 10:32 UTC

**Comment by martinamps** [comment] 2024-07-13 10:38
@pauldambra though I can't speak tot he original nextjs issue, it seems reasonably likely the documentation/instructions provided by PostHog are wrong for remix though. So I'd advocate updating those to mitigate new users people churning or opening issues like this

**Comment by ivanagas** [comment] 2024-07-15 20:14
For Next.js, you can use `next/dynamic` like this:

```
// app/layout.js

import './globals.css'
import { PHProvider } from './providers'
import dynamic from 'next/dynamic'

const PostHogPageView = dynamic(() => import('./PostHogPageView'), {
  ssr: false,
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PHProvider>
        <body>
          <PostHogPageView /> 
          {children}
        </body>
      </PHProvider>
    </html>
  )
}
```

See our docs for more: https://posthog.com/docs/libraries/next-js#app-router

**Comment by maakle** [comment] 2024-08-08 14:32
I am still facing this issue:

My `PHProvider`:

```javascript
"use client";

import posthog from "posthog-js";
import { PostHogProvider } from "posthog-js/react";

import { IS_POSTHOG_ENABLED } from "./client";

if (IS_POSTHOG_ENABLED) {
  posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY!, {
    api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    capture_pageview: false,
    session_recording:
      process.env.NODE_ENV === "production"
        ? {
            maskAllInputs: true,
          }
        : undefined,
  });
}

export function PHProvider({ children }: { children: React.ReactNode }) {
  return <PostHogProvider client={posthog}>{children}</PostHogProvider>;
}
```

Aggregating all my providers like this here here:

```javascript
export function Providers({
  children,
  language,
  currentUser,
}: React.PropsWithChildren<{ language: string; currentUser: User | null }>) {
  return (
    <SessionProvider>
      <CurrentUserProvider serverValue={currentUser}>
        <I18nProvider language={language}>
          <SWRConfig value={SwrConfig}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <PHProvider>{children}</PHProvider>
            </ThemeProvider>
          </SWRConfig>
        </I18nProvider>
      </CurrentUserProvider>
    </SessionProvider>
  );
}
```

And then in `layout/app` I import them:

```javascript
export default async function RootLayout({ children }: React.PropsWithChildren) {
  // ... doing here some stuff around session and language

  return (
    <html lang={lang} suppressHydrationWarning>
      <body>
        <Providers language={lang} currentUser={currentUser}>
          <NextTopLoader color="#6AA0A0" showSpinner={false} />
          <Toaster position="top-right" richColors />
          {children}
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}
```

It still leads to:
<img width="1564" alt="Bildschirmfoto 2024-08-08 um 16 29 31" src="https://github.com/user-attachments/assets/849f0bc7-08ac-4603-9518-0e371a4ccacf">

Though I followed the guides here:
[Posthog Guide](https://posthog.com/docs/libraries/next-js)
[Vercel Guide](https://vercel.com/guides/posthog-nextjs-vercel-feature-flags-analytics)

Any idea how to get this solved?

**Comment by pauldambra** [comment] 2024-08-08 15:10
@maakle I'm not working at the moment so may not react quickly here but... in previous reproductions people shared I completely removed PostHog and they still got the error. In your example the error appears to be to do with a theme. If you completely remove PostHog do you still get the error

**Comment by andlipro** [comment] 2024-08-08 15:18
@maakle , try init posthog inside `PHProvider` in `useEffect`. This is possible solution for many NextJS SSR issues (https://nextjs.org/docs/messages/react-hydration-error)

**Comment by maakle** [comment] 2024-08-08 15:25
I think the issue was added in a newer package. When reverting back to an older version of the sdk e.g. `"posthog-js": "^1.130.2",` it works.

@andlipro your approach also works with the latest `"posthog-js": "^1.154.5"` as of this writing. Thank you!

```javascript
"use client";

import posthog from "posthog-js";
import { PostHogProvider } from "posthog-js/react";
import { useEffect } from "react";

import { IS_POSTHOG_ENABLED } from "./client";

export function PHProvider({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    if (IS_POSTHOG_ENABLED) {
      posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY!, {
        api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST,
        capture_pageview: false,
        session_recording:
          process.env.NODE_ENV === "production"
            ? {
                maskAllInputs: true,
              }
            : undefined,
      });
    }
  }, []);

  return <PostHogProvider client={posthog}>{children}</PostHogProvider>;
}
```

**Comment by pauldambra** [comment] 2024-08-08 15:30
cc @ivanagas for docs inspiration maybe

**Comment by ivanagas** [comment] 2024-08-08 22:07
Ty, documenting here: https://github.com/PostHog/posthog.com/pull/9143

If this doesn't work for someone, please send recreation of issue and I will try to debug.

**Comment by andlipro** [comment] 2024-08-08 22:21
@ivanagas without `if (!posthog.__loaded) {` check it shows warning about double initialization to me. Can we use this check or there are public method instead?

**Comment by ivanagas** [comment] 2024-08-08 22:42
> @ivanagas without `if (!posthog.__loaded) {` check inside `useEffect` it shows warning about double initialization to me. Can we use this check or there are public method instead?

What is the warning? When you call init, the library will check the `__loaded` method itself and return the current instance. See: https://github.com/PostHog/posthog-js/blob/f5a0d12603197deab305a7e25843f04f3fa4c99e/src/posthog-core.ts#L365

**Comment by andlipro** [comment] 2024-08-08 22:52
yes, this warning. I see warning and I assume that calling `init` twice is wrong, and I should take care about this check in my code. But there are no other method to check `__loaded`

**Comment by atomicpages** [comment] 2024-11-07 01:48
Alright for folks passing by using Remix if you're using shadcn or `next-themes` and remix v2 you might be able to get away with adding your posthog script to `root.tsx`. My setup:

```tsx
import { useEffect } from "react";

export function Posthog() {
  useEffect(() => {
    if (typeof window !== "undefined") {
      import("posthog-js")
        .then(({ default: posthog }) => {
          if (!posthog.__loaded) {
            posthog.init(import.meta.env.VITE_POSTHOG_KEY, {
              api_host: "https://us.i.posthog.com",
              person_profiles: "always",
            });
          }
        })
        .catch(console.error);
    }
  }, []);

  return null;
}
```

and in `root.tsx` layout

```tsx
export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
        <Posthog />
      </body>
    </html>
  );
}
```

No more hydrations errors 🎉 hope this helps someone.
