### ISSUE TITLE
Cannot build on AWS Amplify since recent release

### ISSUE THREAD

**Issue by veryayskiy** [PostHog/posthog-js#1031] opened 2024-02-20 03:15 UTC
<img width="1197" alt="Screenshot 2024-02-20 at 10 02 44" src="https://github.com/PostHog/posthog-js/assets/13624984/3222221d-42a8-49d4-a622-85f72e0dd0a7">

When trying to build on AWS Amplify it shows the issue (see screenshot). If manually sets the previous version, e.g. "posthog-js": "1.96.1" it works.

**Comment by pauldambra** [comment] 2024-02-20 08:29
Hey @veryayskiy my guess is this was introduced in 1.106.1 which does reference FormData https://github.com/PostHog/posthog-js/pull/1026/files#diff-1456bfdd728719234cc73d562de1e466fb3deaf6f421417627f91870b2b19c7dR73

Could you check if you can build with 1.106.0 and not with 1.106.1 so we can confirm it is that commit?

But it's not an external dependency, it's (a pretty ancient) part of the DOM https://caniuse.com/?search=formdata https://developer.mozilla.org/en-US/docs/Web/API/FormData

It's a few years since I looked at AWS Amplitude, can you share a little about how you're building the code?

**Comment by veryayskiy** [comment] 2024-02-20 08:44
I checked 1.106.0 - it works great.

Checked with 1.106.1 - crashes with the same error as above. 

So yeah, there is something in between those two versions that crashes it.

**Comment by pauldambra** [comment] 2024-02-20 09:02
I assume that Amplify isn't building in a browser context, so FormData isn't available - although that's surprising to me...

Can you share more about the Amplify build? What I do know is out of date so assume I know nothing... a small reproducible example would be great...

**Comment by veryayskiy** [comment] 2024-02-20 10:34
I'm not sure what can I share...we can have a call so I can show you (DM me on Twitter).

**Comment by xinghengwang** [comment] 2024-02-23 23:07
I am getting this issue also. will have to disable posthog.

**Comment by xinghengwang** [comment] 2024-02-23 23:15
It might be I have server side rendering. A lot of people using server side rendering, since we are importing the library, it should make the server side rendering compatible.

**Comment by veryayskiy** [comment] 2024-02-24 02:17
> Hey @veryayskiy we avoid sync for as long as we can since we've found it's not a great use of everyone's time to figure out overlapping availability just to share config 😊
> 
> You can open a support ticket using https://us.posthog.com/#panel=support%3Asupport%3A%3Alow if you're worried about sharing private information here.
> 
> The important things for me are:
> 
> * are you using typescript
> * if so, does your tsconfig include DOM - https://www.typescriptlang.org/tsconfig#lib
> * "When trying to build on AWS Amplify" what does it mean to "build on AWS Amplify"
>   
>   * e.g. is amplify assuming the code might run in Lambda as well as in a browser
> 
> Certainly the problem here is that your build environment doesn't have a reference for `FormData` but that browser api is >10 years old. So I'm not sure where the fix is

I do not use TS

**Comment by pauldambra** [comment] 2024-02-24 13:23
Hey All,

Thanks for commenting. I can't reproduce this and really do need more info on how y'all are building your software. So appreciate the comments that it is happening for more than one project. But we need a reproducible example or build config or something to start to understand why this works in some environments and not in others

**Comment by Khaledgarbaya** [comment] 2024-02-29 15:33
Happens to me using 

- posthog-js `1.110.0`
- nextjs `13.4.4`

```sh
- error Error [ReferenceError]: FormData is not defined
    at O (/Users/kgarbaya/workspace/personal-website/node_modules/.pnpm/posthog-js@1.110.0/node_modules/posthog-js/dist/module.js:1:5547)
    at K (/Users/kgarbaya/workspace/personal-website/node_modules/.pnpm/posthog-js@1.110.0/node_modules/posthog-js/dist/module.js:1:7088)
    at e.Ci.di.init (/Users/kgarbaya/workspace/personal-website/node_modules/.pnpm/posthog-js@1.110.0/node_modules/posthog-js/dist/module.js:1:125820)
    at Object.<anonymous> (/Users/kgarbaya/workspace/personal-website/node_modules/.pnpm/posthog-js@1.110.0/node_modules/posthog-js/dist/module.js:1:126247)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18) {
  digest: undefined
}
```

**Comment by pauldambra** [comment] 2024-02-29 15:48
Hey @Khaledgarbaya 

Can you share _how_ you're building your software?

This isn't happening for every build including posthog-js and without more detail we can't dig into what is happening for folk where it is 😊

**Comment by Khaledgarbaya** [comment] 2024-02-29 15:57
it's a next.js website using pages route.

1. `pnpm add poshog-js`
2. Add the code snippet from the docs for the pages route section

```js
// pages/_app.js
import posthog from "posthog-js"
import { PostHogProvider } from 'posthog-js/react'

if (typeof window !== 'undefined') { // checks that we are client-side
  posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY, {
    api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST || 'https://app.posthog.com',
    loaded: (posthog) => {
      if (process.env.NODE_ENV === 'development') posthog.debug() // debug mode in development
    },
  })
}

export default function App(
    { Component, pageProps: { session, ...pageProps } }
) {
    return (
        <>
            <PostHogProvider client={posthog}>
                <Component {...pageProps} />
            </PostHogProvider>
        </>
    )
}
```
3. Run `pnpm run dev`
4. visit `localhost:300`

**Comment by pauldambra** [comment] 2024-02-29 16:01
thanks... is it webpack or typescript or js or ....?

**Comment by Khaledgarbaya** [comment] 2024-02-29 16:07
It's a nextjs Typescript project

**Comment by Khaledgarbaya** [comment] 2024-02-29 16:12
The code is public, here is the diff https://github.com/Khaledgarbaya/personal-website/pull/1/files

**Comment by Khaledgarbaya** [comment] 2024-02-29 16:41
Another Update it looks like it only happens on dev mode

**Comment by pauldambra** [comment] 2024-02-29 17:21
interesting thanks... everything looks relatively modern in your dependencies/config 

does it work if you e.g. target es6 instead of es5?

(I think that's a red herring but I couldn't run locally because I'm missing an API key :))

**Comment by deboboy** [comment] 2024-03-04 04:10
Also getting an error trying to deploy on AWS Amplify; using out-of-box Posthog + Next.js 14...

2024-03-04T03:58:32.811Z [WARNING]: Failed to compile.
2024-03-04T03:58:32.819Z [WARNING]: ./app/providers.js
                                    Module not found: Can't resolve 'posthog-js'
                                    https://nextjs.org/docs/messages/module-not-found
                                    ./app/providers.js
                                    Module not found: Can't resolve 'posthog-js/react'

AWS Amplify build settings:
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build

**Comment by pauldambra** [comment] 2024-03-05 13:19
hey @lukasugar @deboboy 

I still don't know how to reproduce this - it's not affecting all customers.

I'd love to fix it too, can you share how you're using/building with posthog?

Without a repro I'm not sure what's causing this...

For e.g. today I had to polyfill `ClipboardEvent` in our tests because it's not included in js-dom. My guess is there's something like this happening where `FormData` is available in the browser (it is ancient after all) but not in some tooling you all are using

**Comment by lukasugar** [comment] 2024-03-05 13:30
Hey @pauldambra, here's some info on how we're using it. I hope it helps:

- it was defined in `packages.json` initially like this: `"posthog-js": "^1.105.9",` and that worked for a few weeks but started breaking recently. This was installing recently the version `1.109.0`. I've removed the "^" and specified `1.106.0` and it's working now.

This should be all/most of the code where we use `post-hog`:
<img width="632" alt="image" src="https://github.com/PostHog/posthog-js/assets/22435018/7be23b83-b76a-4091-af59-c0d0fb15e4ec">
<img width="674" alt="image" src="https://github.com/PostHog/posthog-js/assets/22435018/7b94cb74-8f3e-471c-8013-25dc3f5e419d">
<img width="672" alt="image" src="https://github.com/PostHog/posthog-js/assets/22435018/be9819a3-048c-43b5-828f-24e62e9bcc19">

**Comment by pauldambra** [comment] 2024-03-05 20:19
@lukasugar what we need is info about the environment you're building in - I need a way to recreate the error so I can track it down. I know it isn't affecting all users but I don't know what combination of factors causes it to trigger

**Comment by lukasugar** [comment] 2024-03-06 16:27
@pauldambra I was using `node 16` and `npm 8.X`. After updating npm to 10.5.0 and node to 21.x, it works! So the solution was updating node and npm versions.

**Comment by pauldambra** [comment] 2024-03-06 16:46
That's fantastic info! thanks for taking the time @lukasugar 💖

**Comment by pancho111203** [comment] 2024-03-08 15:02
The code should be a no-op if it's running on the server...

Also, I upgraded to node 17 and still have the same error. I can't upgrade to 18+ due to a limitation with Amplify

**Comment by pauldambra** [comment] 2024-03-08 19:27
> The code should be a no-op if it's running on the server...

posthog-js isn't for running on a server, there's posthog-node for backend usage

**Comment by hamishirving** [comment] 2024-05-21 19:34
Hey @pauldambra checking if you saw this pretty thorough investigation on a different but (looks like) related issue?

https://github.com/PostHog/posthog-js/issues/1139#issuecomment-2081179408

I've just upgraded to latest posthog-js version and am getting errors while pre-rendering in my Redwood JS app deployed on  Netlify (causes my deploy to timeout). Node 20.9.0, Yarn 3.5.0

`[PostHog.js] was already loaded elsewhere. This may cause issues.`

**Comment by pauldambra** [comment] 2024-07-11 17:28
I'm going to close this since AWS Ampllify supports Node 18 and Node 18 supports FormData, so there's a route forward (I believe) for folk here

@hamishirving your comment on the other issue is super thorough but I think unrelated to this issue 👍

**Closed by pauldambra** 2024-07-11 17:28 UTC

**Comment by franciscorubin** [comment] 2024-12-17 07:20
> > The code should be a no-op if it's running on the server...
> 
> posthog-js isn't for running on a server, there's posthog-node for backend usage

I believe this issue happens when running NextJS with server side rendering, which makes it run on the server. There is no use of posthog-js on the server, so it should be a no-op instead of failing. Another solution is to force load it only on the client using https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#nextdynamic

**Comment by jyotiprakashh** [comment] 2025-03-08 14:46
For current version it works on 1.229.2 version. So if anybody facing that issue can try it out!
